name: test_app
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.4
  awesome_notifications: ^0.9.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  json_serializable: ^6.7.1


flutter:


  uses-material-design: true

  